Algoritmo "Atribuicao"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Arsenio  Soto 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 6/19/2021
Var
// Seção de Declarações das variáveis 
   msg: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   msg <- "Arsenio Jose soto"
   Escreval(msg)
Fimalgoritmo