Algoritmo "CalculandoOSenoDeUmGrau"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Arsenio  Soto 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 6/19/2021
Var
// Seção de Declarações das variáveis 
    a: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

     a <- sen (graupRad(90))
     Escreval(a)
Fimalgoritmo