Algoritmo "ConversaoDeCelsosParaFarahaite"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Arsenio  Soto 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 6/19/2021
Var
// Seção de Declarações das variáveis 
   f, c: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreval("Temperactura em faraheith")
   Leia(f)
   c <- (f - 32)/1.8
    Escreval(c)
Fimalgoritmo